---
# 1.6.1.1 Ensure SELinux is not disabled in bootloader configuration (Scored)

- name: 1.6.1.1 Ensure SELinux is not disabled in bootloader configuration (Scored)
  replace:
    dest: /etc/default/grub
    regexp: '(selinux|enforcing)\s*=\s*0\s*'
    follow: yes
    register: selinux_grub_patch
  ignore_errors: yes
  when: not cis_selinux_disabled
  tags:
    - level2
    - section1
    - section1_level2
    - scored
    - "1.6.1.1"
  notify: generate new grub config
